//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMarketing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_product
    {
        public int pro_id { get; set; }
        public string pro_name { get; set; }
        public string pro_image { get; set; }
        public Nullable<int> pro_price { get; set; }
        public Nullable<int> pro { get; set; }
        public Nullable<int> prod { get; set; }
        public string pro_des { get; set; }
    
        public virtual tb1_category tb1_category { get; set; }
        public virtual tbl_user tbl_user { get; set; }
    }
}
